import React from "react";
import psImg1 from "../../assets/play-store-3.png";
import psImg2 from "../../assets/play-store-4.png";
import { ChevronDownIcon } from "@radix-ui/react-icons";
import "./Footer.css";
import * as Accordion from "@radix-ui/react-accordion";
import classNames from "classnames";
import * as Dialog from '@radix-ui/react-dialog';
import { Cross2Icon } from '@radix-ui/react-icons';



import img1 from "../../assets/footer-1.jpg";
import img2 from "../../assets/footer-2.jpg";
import img3 from "../../assets/footer-3.jpg";
import img4 from "../../assets/footer-4.jpg";
import img5 from "../../assets/footer-5.jpg";
import img6 from "../../assets/footer-6.jpg";
import img7 from "../../assets/footer-7.jpg";
import img8 from "../../assets/job.jpg";
import img9 from "../../assets/beyoung-cover.jpg";


import { useScreenSize } from "../CommonFunctions/CommonFunctions";

const Footer = () => {
  const screenSize = useScreenSize();
  const isMobile = screenSize < 960;

  const content = (
    <div className="flex flex-col gap-4 bg-black text-white justify-center items-center">
    <div className="flex flex-row flex-wrap gap-4 bg-black text-white justify-around p-4 w-[70%]">
      <div className = {`${isMobile ? 'w-full' : '' }`} >
        <h2 className="text-yellow-200 font-bold">NEED HELP</h2>
        <div>
          
          <Dialog.Root>
            <Dialog.Trigger asChild>
              <button className="ButtonFooter violetFooter">Contact Us</button>
            </Dialog.Trigger>
            <Dialog.Portal>
              <Dialog.Overlay className="DialogOverlay" />
              <Dialog.Content className="DialogContentFooter">
                <div className="">
                  <p className="text-green-300 text-[1.2rem]" >
                    Getting help is easy
                  </p>
                  <p className="text-[0.8rem] font-bold my-2">
                    Hello there, nice to see you !
                  </p>
                  <div className="my-4">
                    Send us a mail at <span className="font-bold">support@beyoung.in</span> , and we'll work our magic!
                  </div>
                </div>
                <Dialog.Close asChild>
                  <button className="IconButton" aria-label="Close">
                    <Cross2Icon />
                  </button>
                </Dialog.Close>
              </Dialog.Content>
            </Dialog.Portal>
          </Dialog.Root>

        </div>
        <div>
          
          <Dialog.Root>
            <Dialog.Trigger asChild>
              <button className="ButtonFooter violetFooter">Track Order</button>
            </Dialog.Trigger>
            <Dialog.Portal>
              <Dialog.Overlay className="DialogOverlay" />
              <Dialog.Content className="DialogContentFooter">
                <div className="m-2">
                  <p className="my-3 text-green-300 text-[1.2rem]">Live Tracking</p>
                  <p className="font-semibold my-3">
                    This feature is set to be included in the forthcoming updates.
                  </p>
                </div>
                <Dialog.Close asChild>
                  <button className="IconButton" aria-label="Close">
                    <Cross2Icon />
                  </button>
                </Dialog.Close>
              </Dialog.Content>
            </Dialog.Portal>
          </Dialog.Root>  
          
        </div>
        <div>
          <Dialog.Root>
            <Dialog.Trigger asChild>
              <button className="ButtonFooter violetFooter">Returns & Refunds</button>
            </Dialog.Trigger>
            <Dialog.Portal>
              <Dialog.Overlay className="DialogOverlay" />
              <Dialog.Content className="DialogContentFooter">
                <div className="m-2 h-[300px] overflow-auto">
                  <p className="text-center my-4 font-bold text-[1.1rem]">Return & Exchange Policy</p>
                  <div>
                    <ul>
                      <li>1. The return or exchange can be done within 15 days after your order is delivered.</li>
                      <li>2. In case the customer receives defective/wrong product(s), the reverse pickup will be generated by us and the shipping charges will be covered by us only.</li>
                      <li>3. Note: It is mandatory to capture a video/photo before shipping the package or handling it to our courier partner.</li>
                      <li>4. If the customer's pin code is non-serviceable by our courier partners, then the customer is liable to self-ship the product(s) and the shipping charges upto ₹100 are 100% refundable if customer receives defective/wrong product(s).</li>
                      <li>5. Please courier the product(s) to the following address:
Beyoung Folks Pvt. Ltd. Eklingpura Chouraha, Ahmedabad Main Road (NH 8 - Near Mahadev Hotel) Udaipur, India 313002</li>
                      <li>6. Kindly pack the product(s) properly to prevent damage during transit. Please ensure the product(s) must be in unused condition with all tags and packaging.</li>
                      <li>7. Due to hygiene concerns of our customers, we do not accept return/refund or perform an exchange for the Boxer Shorts.</li>
                      <li>8. Note: We suggest you to select 'Speed Post' as your courier service rather than using other courier companies. Speed Post is a government-owned entity that operates India's largest postal network and it is totally reliable</li>
                    </ul>
                  </div>
                  <p className="text-center my-4 font-bold text-[1.1rem]">Refund Policy</p>
                  <div>
                    <ul>
                      <li>1. Prepaid Orders: The refund for the prepaid order will be processed within 7 working days after receiving your order at the warehouse and Quality Check of the product(s). The Refund Amount will be reflected in the respective payment mode.</li>
                      <li>2. Note: If you've placed a prepaid order using a Refund Coupon, the Value of the Coupon Code will be refunded through a Coupon and the remaining amount will be paid through your original payment mode.</li>
                      <li>3. For COD Orders: A coupon code of the ordered value will be sent to your registered email address/contact number within 48 hours after receiving your order at the warehouse and Quality Check of the product(s).</li>                      
                    </ul>
                  </div>

                </div>
                <Dialog.Close asChild>
                  <button className="IconButton" aria-label="Close">
                    <Cross2Icon />
                  </button>
                </Dialog.Close>
              </Dialog.Content>
            </Dialog.Portal>
          </Dialog.Root> 
        </div>
        <div>
          
          <Dialog.Root>
            <Dialog.Trigger asChild>
              <button className="ButtonFooter violetFooter">FAQ's</button>
            </Dialog.Trigger>
            <Dialog.Portal>
              <Dialog.Overlay className="DialogOverlay" />
              <Dialog.Content className="DialogContentFooter">
                <div className="m-2 h-[300px] overflow-auto">
                  <p className="text-center my-4 font-bold text-[1.1rem]">General FAQ questions with answers Policy</p>
                  <div>
                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: How can I track my order?</h2>
                      <p className="text-gray-600">A: To track your order, log in to your account and go to the "Order History" section. There, you'll find a list of your recent orders with tracking information.</p>
                    </div>

                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: What is your return policy?</h2>
                      <p className="text-gray-600">A: We have a 30-day return policy. If you're not satisfied with your purchase, you can return it within 30 days of receipt. Please review our Return Policy for more details.</p>
                    </div>

                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: How do I change my account password?</h2>
                      <p className="text-gray-600">A: You can change your password by logging in to your account, going to the "Account Settings" page, and selecting the "Change Password" option. Follow the on-screen instructions to update your password.</p>
                    </div>

                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: Do you offer international shipping?</h2>
                      <p className="text-gray-600">A: Yes, we offer international shipping to many countries. You can check the list of countries we ship to during the checkout process. Shipping fees and delivery times may vary based on your location.</p>
                    </div>

                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: What payment methods do you accept?</h2>
                      <p className="text-gray-600">A: We accept a variety of payment methods, including major credit cards (Visa, MasterCard, etc.), PayPal, and Apple Pay. You can choose your preferred payment option at checkout.</p>
                    </div>

                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: How can I contact customer support?</h2>
                      <p className="text-gray-600">A: You can reach our customer support team by visiting our Contact Us page or by emailing support@example.com. We're here to assist you with any questions or issues you may have.</p>
                    </div>

                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: Can I change my shipping address after placing an order?</h2>
                      <p className="text-gray-600">A: You can update your shipping address before your order is shipped. Please contact our customer support as soon as possible to make the necessary changes. Once your order has shipped, address updates may not be possible.</p>
                    </div>

                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: How long does shipping take?</h2>
                      <p className="text-gray-600">A: Shipping times vary depending on your location and the shipping method you choose at checkout. Standard shipping typically takes 3-5 business days, while expedited shipping may arrive within 1-2 business days. International shipping times may vary.</p>
                    </div>

                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: Do you offer discounts or promotions?</h2>
                      <p className="text-gray-600">A: Yes, we frequently offer discounts and promotions. Keep an eye on our Promotions page to stay updated on our latest deals and special offers.</p>
                    </div>

                    <div className="bg-white rounded-lg shadow p-4 mb-4">
                      <h2 className="text-lg font-semibold mb-2">Q: What is your privacy policy?</h2>
                      <p className="text-gray-600">A: We take your privacy seriously. You can review our Privacy Policy for information on how we collect, use, and protect your personal data.</p>
                    </div>

                  </div>
                </div>
                <Dialog.Close asChild>
                  <button className="IconButton" aria-label="Close">
                    <Cross2Icon />
                  </button>
                </Dialog.Close>
              </Dialog.Content>
            </Dialog.Portal>
          </Dialog.Root> 
        </div>
        <div>

        <Dialog.Root>
            <Dialog.Trigger asChild>
              <button className="ButtonFooter violetFooter">Career</button>
            </Dialog.Trigger>
            <Dialog.Portal>
              <Dialog.Overlay className="DialogOverlay" />
              <Dialog.Content className="DialogContentFooter">
                <div className="m-2 h-[300px] overflow-auto">
                  <img src={img8} className="h-[180px] object-cover" alt="" />
                  <p className="text-center my-4 font-bold text-[1.1rem]">Join Beyoung Family</p>
                  <div className="text-[0.8rem]">
                    Stay tuned for future job opportunities, and please feel free to send your latest resume to the following email address.
                  </div>
                  <p className="text-green-400">support@beyoung.in</p>
                </div>
                <Dialog.Close asChild>
                  <button className="IconButton" aria-label="Close">
                    <Cross2Icon />
                  </button>
                </Dialog.Close>
              </Dialog.Content>
            </Dialog.Portal>
        </Dialog.Root> 

        </div>
      </div>
      <div className = {`${isMobile ? 'w-full' : '' }`} >
        <h2 className="text-yellow-200 font-bold">COMPANY</h2>
        <div>
          
          <Dialog.Root>
            <Dialog.Trigger asChild>
              <button className="ButtonFooter violetFooter">About Us</button>
            </Dialog.Trigger>
            <Dialog.Portal>
              <Dialog.Overlay className="DialogOverlay" />
              <Dialog.Content className="DialogContentFooter">
                <div className="m-2 h-[300px] overflow-auto">
                  <img src={img9} className=" object-contain" alt="" />
                  <p className="text-center my-4 font-bold text-[1.1rem]">BeYOUng About Us</p>
                  <p className="text-center my-4 font-bold text-[0.9rem]">Our Story: Get the Young Out With Beyoung</p>
                  <div>
                  <p>
                    The story of Be Young is very simple and holds the essence of vision, hard work, and perseverance. Beyoung runs with the idea of providing the best to the customers because there is no feeling better than customer satisfaction. The prime focus of Be Young is to create products that represent the young souls by acting as a replica of their thoughts, personality, and choices.
                  </p>
                  <p>
                    Be Young was born in the year 2017, with the idea of four creative souls whose prime purpose was to establish an e-commerce brand that represents the common Indian young souls when it comes to fashion and accessories with distinctive and out of box designs and trendy product range.
                  </p>
                  <p>
                    The idea of Beyoung.in is to represent young souls of today, who believe in speaking their heart and mind with the choices they make. The growth of Beyoung as a brand says a story about being dynamic in what you believe. The BeYOUng Folks started by some creative souls in a small room with a leap of faith to become a brand that wins over customer’s trust with every product presented to them. Be Young as a brand focuses on creating products that Beyoungsters can carry with them to represent their style, opinions, and personality while maintaining relevance to the latest fashion trends. Whatever we manufacture, whatever we create, or whatever we present to you, we make sure that it has the heart and soul of Be “Young'' in it.
                  </p>


                  </div>

                  
                  
                </div>
                <Dialog.Close asChild>
                  <button className="IconButton" aria-label="Close">
                    <Cross2Icon />
                  </button>
                </Dialog.Close>
              </Dialog.Content>
            </Dialog.Portal>
        </Dialog.Root> 
        </div>
        <div>Beyoung Blog</div>
        <div>Beyoungistan</div>
        <div>Collaboration</div>
        <div>Media</div>
      </div>
      <div className = {`${isMobile ? 'w-full' : '' }`} >
        <h2 className="text-yellow-200 font-bold">MORE INFO</h2>
        <div>Terms and Conditions</div>
        <div>Privacy Policy</div>
        <div>Shipping Policy</div>
        <div>Sitemap</div>
      </div>
      <div className = {`${isMobile ? 'w-full' : '' }`} >
        <h2 className="text-yellow-200 font-bold">Location</h2>
        <div>support@beyoung.in</div>
        <div className="max-w-[130px]">
          Eklingpura Chouraha, Ahmedabad Main Road (NH 8- Near Mahadev
          Hotel) Udaipur, India- 313002
        </div>

        <h2>DOWNLOAD THE APP</h2>
        <div className="flex flex-col p-2 gap-3">
          <img className="max-w-[130px]" src={psImg1} alt="img" />
          <img className="max-w-[130px]" src={psImg2} alt="img" />
        </div>
      </div>
    </div>
    <div className="flex justify-center w-[70%]">
      <Accordion.Root
        className="AccordionRoot bg-black"
        type="single"
        defaultValue="item-1"
        collapsible
      >
        <div className="border m-4"></div>
        <Accordion.Item className="AccordionItem bg-black" value="item-1">
          <AccordionTrigger className="bg-black">WHY CHOOSE US?</AccordionTrigger>
          <AccordionContent>
            <div>Online Shopping Site</div>
            <div>
              India's Best Online Shopping Site for Fashion and Lifestyle
            </div>
            <div>
              Started in 2018, Beyoung is the Best Site for online shopping
              in India when it comes to a vast collection of men's and
              women's fashion. The latest trends and styles are showcased
              here, yes at your favorite online fashion store. Well, if
              fashion is medicine, then Be Young is the chemist shop where
              you can do your online shopping for fashion with ease. Nothing
              to brag about, but we are the classic blend of 'Creativity'
              and 'Style'. Get The Young Out with Beyoung, our slogan says a
              lot about us.
            </div>
          </AccordionContent>
        </Accordion.Item>
        <div className="border m-4"></div>

        <Accordion.Item className="AccordionItem" value="item-3">
          <AccordionTrigger>POPULAR CATEGORIES</AccordionTrigger>
          <AccordionContent>
            <div className="text-yellow-200 font-bold pt-4 ">Men' Clothing</div>
            <div>
              Topwear: Half Sleeve T-Shirts | Full Sleeve T-Shirts | Men's
              Shirts | Printed T-Shirts | Plain T-Shirts | Polo T-Shirts |
              Plus Size T-Shirts | Combos
            </div>
            <div className="h-[20px]"></div>
            <div>
              Theme Based T Shirts: Ipl T Shirts | Men's Travel T-shirts |
              Gym T Shirts | Quotes T Shirt | Cartoon T Shirt | Entrepreneur
              T-Shirts | Student T Shirts | Funky T Shirts
            </div>
            <div className="h-[20px]"></div>
            <div>
              Winter Collection: Hoodies for Men | Sweatshirts for Men |
              Jackets for Men
            </div>
            <div className="text-yellow-200 font-bold pt-4 ">WOMEN' Clothing</div>
            <div>
              Topwear: Women Shirts | Half Sleeve T-Shirts | Full Sleeve
              T-Shirts | Printed T-Shirts | Plain T-Shirts | Crop Tops |
              Plus Size T-Shirts | kurti
            </div>
            <div className="h-[20px]"></div>
            <div>
              Theme Based T Shirts: Women's Travel T-shirts | Feminist
              T-shirts
            </div>
            <div className="h-[20px]"></div>
            <div>
              Winter Collection: Hoodies for Women | Sweatshirts for Women |
              Long Coats for Women
            </div>
            <div className="h-[20px]"></div>
            <div>CUSTOMIZATION</div>
            <div>Custom T Shirt</div>
            <div className="h-[20px]"></div>
            <div>COUPLE WEAR</div>
            <div>Couple Boxer | Couple T shirts</div>
            <div className="h-[20px]"></div>
            <div>BOTTOMWEAR:</div>
            <div>
              Mens Boxer | Womens Boxer | Jeggings | Men Sweatpants | Mens
              Joggers | Chino Pants | Mens Jeans | Mens Pyjamas
            </div>
          </AccordionContent>
        </Accordion.Item>
        <div className="border m-4"></div>
      </Accordion.Root>
    </div>
    {!isMobile &&
      <div className="flex flex-row  gap-4 justify-center w-[70%] justify-center">
      <div className="w-1/2 flex flex-col justify-center ">
        <p className="p-4 text-[1.2rem] font-bold">
          100% SECURE PAYMENT
        </p>
        <img className="w-[99%]" src={img1} alt="img" />
      </div>
      <div className="border"></div>
      <div className="w-1/2 px-4">
        <p className="p-4 text-[1.2rem] font-bold">
          LET'S BE FRIENDS
        </p>
        <div className="flex  flex-row gap-[20px] justify-between w-[50%]">
          <img className="w-[30px]" src={img2} alt="img" />
          <img className="w-[30px]" src={img3} alt="img" />
          <img className="w-[30px]" src={img4} alt="img" />
          <img className="w-[30px]" src={img5} alt="img" />
          <img className="w-[30px]" src={img6} alt="img" />
          <img className="w-[30px]" src={img7} alt="img" />
        </div>
      </div>
      </div>
    }
    {isMobile && 
      <div className="flex flex-col  gap-2 justify-center w-[70%] justify-center">
        <div className="px-2 flex flex-row justify-center items-center">
          <p className="p-2 text-[0.8em] font-[700]">
            LET'S BE FRIENDS
          </p>              
          <div className="flex flex-row gap-[10px] justify-around  w-[50%]">
            <img className="w-[15px]" src={img2} alt="img" />
            <img className="w-[15px]" src={img3} alt="img" />
            <img className="w-[15px]" src={img4} alt="img" />
            <img className="w-[15px]" src={img5} alt="img" />
            <img className="w-[15px]" src={img6} alt="img" />
            <img className="w-[15px]" src={img7} alt="img" />
          </div>
        </div>
        <div className="flex flex-col justify-center ">
          <img className="w-[99%]" src={img1} alt="img" />
        </div>            
      </div>
    }

    <div className="py-[2rem] font-bold text-center">
      Copyright © 2023 Raviprasaath. All rights reserved.
    </div>
    </div>
  )
  
  return (
    <>
      {isMobile && (
        <Accordion.Root className="AccordionRoot bg-black" type="single" defaultValue="item-1" collapsible >
          <Accordion.Item className="AccordionItem" value="item-1">
            <AccordionTrigger className="bg-black justify-center gap-4" >
              ABOUT BEYOUNG
            </AccordionTrigger>
              <AccordionContent> 
                {content}          
              </AccordionContent>
          </Accordion.Item>
        </Accordion.Root>
      )}
      {!isMobile && 
        <div>
          {content}
        </div>
      } 
    </>
  );
};

const AccordionTrigger = React.forwardRef(
  ({ children, className, ...props }, forwardedRef) => (
    <Accordion.Header className={classNames("AccordionHeader", className)}>
      <Accordion.Trigger
        className={classNames("AccordionTrigger text-[1.2rem] font-[700] text-yellow-400", className)}
        {...props}
        ref={forwardedRef}
      >
        {children}
        <ChevronDownIcon className="AccordionChevron" aria-hidden />
      </Accordion.Trigger>
    </Accordion.Header>
  )
);

const AccordionContent = React.forwardRef(
  ({ children, className, ...props }, forwardedRef) => (
    <Accordion.Content
      className={classNames("AccordionContent", className)}
      {...props}
      ref={forwardedRef}
    >
      <div className="AccordionContentText bg-black">{children}</div>
    </Accordion.Content>
  )
);

export default Footer;




